/**
 * Dreams CRMS Tabler icon set — names match
 * https://crms.dreamstechnologies.com/html/leads.html (`ti ti-*`).
 */
import { createCrmTiIcon, CrmTiIcon } from "@/components/crm/ui/CrmTiIcon";

export { CrmTiIcon, createCrmTiIcon };

/** Shared chrome icons (page header, toolbar, kanban, forms) */
export const CrmIcon = {
  Filter: createCrmTiIcon("filter"),
  Search: createCrmTiIcon("search"),
  Export: createCrmTiIcon("package-export"),
  Refresh: createCrmTiIcon("refresh"),
  Collapse: createCrmTiIcon("transition-top"),
  Expand: createCrmTiIcon("transition-bottom"),
  SidebarCollapse: createCrmTiIcon("arrow-bar-to-left"),
  SidebarExpand: createCrmTiIcon("arrow-bar-to-right"),
  Import: createCrmTiIcon("file-import"),
  ChevronDown: createCrmTiIcon("chevron-down"),
  ChevronRight: createCrmTiIcon("chevron-right"),
  Plus: createCrmTiIcon("plus"),
  AddFilled: createCrmTiIcon("square-rounded-plus-filled"),
  DotsVertical: createCrmTiIcon("dots-vertical"),
  ListView: createCrmTiIcon("list-tree"),
  GridView: createCrmTiIcon("grid-dots"),
  CardView: createCrmTiIcon("layout-grid"),
  Calendar: createCrmTiIcon("calendar"),
  X: createCrmTiIcon("x"),
  Menu: createCrmTiIcon("menu-deep"),
  Maximize: createCrmTiIcon("maximize"),
  Minimize: createCrmTiIcon("minimize"),
  Help: createCrmTiIcon("help-hexagon"),
  ChartPie: createCrmTiIcon("chart-pie"),
  Bell: createCrmTiIcon("bell-check"),
  Apps: createCrmTiIcon("layout-grid-add"),
  Moon: createCrmTiIcon("moon"),
  SearchHeader: createCrmTiIcon("search"),
  Mail: createCrmTiIcon("mail"),
  Phone: createCrmTiIcon("phone"),
  Message: createCrmTiIcon("message-circle-2"),
  Palette: createCrmTiIcon("color-swatch"),
  PhoneCall: createCrmTiIcon("phone-check"),
  MapPin: createCrmTiIcon("map-pin-pin"),
  Money: createCrmTiIcon("report-money"),
  Lock: createCrmTiIcon("lock"),
  Logout: createCrmTiIcon("logout"),
  Check: createCrmTiIcon("check"),
  Settings: createCrmTiIcon("settings"),
  FilePdf: createCrmTiIcon("file-type-pdf"),
  FileXls: createCrmTiIcon("file-type-xls"),
  Trash: createCrmTiIcon("trash"),
  Columns: createCrmTiIcon("columns-3"),
  GitBranch: createCrmTiIcon("git-branch"),
  Activity: createCrmTiIcon("activity"),
  Eye: createCrmTiIcon("eye"),
  EyeOff: createCrmTiIcon("eye-off"),
  MailOpen: createCrmTiIcon("mail-opened"),
  MailPlus: createCrmTiIcon("mail-plus"),
  MailX: createCrmTiIcon("mail-x"),
  Reply: createCrmTiIcon("arrow-back-up"),
  FilterOff: createCrmTiIcon("filter-off"),
  Timer: createCrmTiIcon("clock"),
  Loader: createCrmTiIcon("loader-2"),
  Users: createCrmTiIcon("users"),
  Target: createCrmTiIcon("target"),
  Inbox: createCrmTiIcon("inbox"),
  ListTodo: createCrmTiIcon("list-check"),
  ArrowRight: createCrmTiIcon("arrow-right"),
  TrendingUp: createCrmTiIcon("trending-up"),
  CheckCircle: createCrmTiIcon("circle-check"),
  AlertTriangle: createCrmTiIcon("alert-triangle"),
  Download: createCrmTiIcon("download"),
  Upload: createCrmTiIcon("upload"),
  Pencil: createCrmTiIcon("pencil"),
  Copy: createCrmTiIcon("copy"),
  Handshake: createCrmTiIcon("medal"),
} as const;

/** Sidebar / nav icons — aligned to CRMS menu glyphs where possible */
export const CrmNavIcon = {
  Dashboard: createCrmTiIcon("dashboard"),
  Applications: createCrmTiIcon("brand-airtable"),
  Contacts: createCrmTiIcon("user-up"),
  Companies: createCrmTiIcon("building-community"),
  Deals: createCrmTiIcon("medal"),
  Leads: createCrmTiIcon("chart-arcs"),
  Pipeline: createCrmTiIcon("timeline-event-exclamation"),
  Proposals: createCrmTiIcon("file-star"),
  Contracts: createCrmTiIcon("file-check"),
  Estimates: createCrmTiIcon("file-report"),
  Invoices: createCrmTiIcon("file-invoice"),
  Payments: createCrmTiIcon("report-money"),
  Analytics: createCrmTiIcon("chart-bar"),
  Activities: createCrmTiIcon("bounce-right"),
  Projects: createCrmTiIcon("atom-2"),
  Tasks: createCrmTiIcon("list-check"),
  Milestones: createCrmTiIcon("stack-2"),
  Timesheets: createCrmTiIcon("clock-record"),
  Box: createCrmTiIcon("box"),
  Users: createCrmTiIcon("users"),
  UsersGroup: createCrmTiIcon("users-group"),
  UserCheck: createCrmTiIcon("user-check"),
  UserStar: createCrmTiIcon("user-star"),
  World: createCrmTiIcon("world"),
  Briefcase: createCrmTiIcon("briefcase"),
  Target: createCrmTiIcon("target"),
  Mail: createCrmTiIcon("mail"),
  Calendar: createCrmTiIcon("calendar"),
  Notes: createCrmTiIcon("notes"),
  Phone: createCrmTiIcon("phone"),
  Message: createCrmTiIcon("message-circle-2"),
  Bell: createCrmTiIcon("bell"),
  Bot: createCrmTiIcon("robot"),
  Sparkles: createCrmTiIcon("sparkles"),
  GitBranch: createCrmTiIcon("git-branch"),
  TrendingUp: createCrmTiIcon("trending-up"),
  Activity: createCrmTiIcon("activity"),
  Layers: createCrmTiIcon("stack-2"),
  LayoutGrid: createCrmTiIcon("layout-grid"),
  ListTodo: createCrmTiIcon("list"),
  Settings: createCrmTiIcon("settings"),
  Search: createCrmTiIcon("search"),
  Handshake: createCrmTiIcon("medal"),
  Building: createCrmTiIcon("building-community"),
  Package: createCrmTiIcon("box"),
  ScrollText: createCrmTiIcon("file-star"),
  FileText: createCrmTiIcon("file-text"),
  CheckCircle: createCrmTiIcon("circle-check"),
  Contact: createCrmTiIcon("user-up"),
  Globe: createCrmTiIcon("world"),
  BarChart: createCrmTiIcon("chart-bar"),
  MailSearch: createCrmTiIcon("mail-search"),
} as const;
