/**
 * Core document keys that may receive merged values when a custom field is deleted.
 * Keep in sync with portal `custom-field-merge-targets.ts`.
 */
export const CUSTOM_FIELD_MERGEABLE_CORE: Record<string, Set<string>> = {
  leads: new Set([
    'salutation',
    'firstName',
    'middleName',
    'lastName',
    'email',
    'mobileNo',
    'phone',
    'organization',
    'jobTitle',
    'website',
    'linkedinUrl',
    'source',
    'industry',
    'noOfEmployees',
    'territory',
    'leadOwner',
    'stage',
    'status',
  ]),
  contacts: new Set([
    'salutation',
    'firstName',
    'middleName',
    'lastName',
    'email',
    'mobileNo',
    'phone',
    'organization',
    'jobTitle',
    'website',
    'linkedinUrl',
    'source',
    'industry',
    'noOfEmployees',
    'territory',
    'leadOwner',
    'stage',
    'status',
    'telegram',
    'address',
    'gender',
  ]),
  deals: new Set([
    'title',
    'stage',
    'organization',
    'dealOwner',
    'nextStep',
    'currency',
  ]),
  organizations: new Set([
    'name',
    'website',
    'territory',
    'industry',
    'noOfEmployees',
    'phone',
    'email',
    'address',
  ]),
  clients: new Set(['name', 'email', 'phone', 'status']),
};
