/** Reference list for template authors; mirrors server-side merge keys from `EmailTemplateMergeService`. */
export const EMAIL_TEMPLATE_MERGE_GROUPS: { title: string; fields: string[] }[] = [
  {
    title: "Recipient (person)",
    fields: [
      "salutation",
      "firstName",
      "lastName",
      "fullName",
      "email",
      "phone",
      "mobileNo",
      "jobTitle",
      "companyName",
      "company",
      "organization",
      "website",
      "industry",
      "noOfEmployees",
      "territory",
      "stage",
      "status",
      "source",
      "leadOwner",
      "linkedinUrl",
    ],
  },
  {
    title: "Linked company (account)",
    fields: [
      "accountName",
      "accountWebsite",
      "accountIndustry",
      "accountEmployees",
      "accountTerritory",
      "accountPhone",
      "accountEmail",
      "accountAddress",
    ],
  },
  {
    title: "Deal",
    fields: [
      "dealTitle",
      "title",
      "dealValue",
      "dealValueFormatted",
      "expectedDealValue",
      "expectedDealValueFormatted",
      "currency",
      "probability",
      "expectedClosureDate",
      "nextStep",
      "dealOwner",
    ],
  },
  {
    title: "Deal — linked lead",
    fields: [
      "leadFirstName",
      "leadLastName",
      "leadFullName",
      "leadEmail",
      "leadPhone",
      "leadJobTitle",
      "leadCompany",
    ],
  },
  {
    title: "Deal — primary contact",
    fields: [
      "contactSalutation",
      "contactFirstName",
      "contactLastName",
      "contactFullName",
      "contactEmail",
      "contactPhone",
      "contactJobTitle",
      "contactCompany",
    ],
  },
  {
    title: "Organization record",
    fields: [
      "name",
      "companyName",
      "website",
      "industry",
      "territory",
      "noOfEmployees",
      "phone",
      "email",
      "address",
    ],
  },
  {
    title: "Client record",
    fields: ["name", "fullName", "email", "phone", "status"],
  },
  {
    title: "You (sender)",
    fields: [
      "senderFirstName",
      "senderLastName",
      "senderFullName",
      "myName",
      "senderEmail",
    ],
  },
  {
    title: "Date",
    fields: ["today", "todayLong"],
  },
  {
    title: "Custom fields",
    fields: ["custom_<fieldKey>"],
  },
];
